# Aranea tmux status fragment
set -g status-style 'bg=#050609,fg=#8b96a6'
set -g status-left '#[fg=#3bff9e] ◈ #[fg=#e7ecf3]#S '
set -g status-left-length 32
set -g window-status-format '#[fg=#8b96a6] #I:#W '
set -g window-status-current-format '#[fg=#08090b,bg=#3bff9e] #I:#W '
set -g status-right '#[fg=#7a5cff]%Y-%m-%d #[fg=#e7ecf3]%H:%M '
set -g pane-border-style 'fg=#3a4250'
set -g pane-active-border-style 'fg=#3bff9e'
