# Aranea Foot palette
[colors]
foreground=e7ecf3
background=08090b
selection-foreground=e7ecf3
selection-background=1c2b22
cursor=08090b 3bff9e
regular0=050609
regular1=ff5f56
regular2=3bff9e
regular3=ffbd2e
regular4=5b8cff
regular5=7a5cff
regular6=5ce0c6
regular7=c7d0db
bright0=3a4250
bright1=ff8a80
bright2=7dffc0
bright3=ffd166
bright4=8fb4ff
bright5=8f75ff
bright6=8ff5df
bright7=ffffff
